Multinomial Logistic regression

In [36]:
import pandas as pd

data = pd.read_csv("./Training_Data.csv")
data.describe()

,number_of_maps,firepower,entrying,trading,opening,clutching,sniping,utility,igl
count,175.000000,175.000000,175.000000,175.000000,175.000000,175.000000,175.000000,175.000000,175.000000
mean,50.108571,54.708571,48.554286,47.342857,53.548571,50.885714,20.542857,58.771429,0.194286
std,16.175925,24.174668,25.217586,20.248943,22.222146,17.346985,37.558493,18.594409,0.396785
min,14.000000,2.000000,5.000000,6.000000,5.000000,18.000000,0.000000,17.000000,0.000000
25%,37.000000,35.000000,29.500000,31.500000,35.000000,38.000000,0.000000,45.500000,0.000000
50%,51.000000,55.000000,47.000000,47.000000,52.000000,48.000000,0.000000,58.000000,0.000000
75%,58.000000,73.500000,69.000000,62.000000,75.000000,65.000000,3.500000,72.500000,0.000000
max,106.000000,100.000000,98.000000,96.000000,97.000000,91.000000,95.000000,95.000000,1.000000

In [37]:
for col in [
    "firepower",
    "entrying",
    "trading",
    "opening",
    "clutching",
    "sniping",
    "utility",
]:
    data[col] = data[col] / 100

data.head()

,name,position,number_of_maps,firepower,entrying,trading,opening,clutching,sniping,utility,igl
0,alex666,Closer,83,0.27,0.44,0.43,0.26,0.58,0.00,0.61,1
1,npl,Opener,83,0.85,0.44,0.60,0.76,0.47,0.00,0.48,0
2,kensizor,Opener,83,0.70,0.94,0.56,0.63,0.37,0.00,0.41,0
3,esenthial,Linchpin,83,0.31,0.40,0.79,0.22,0.61,0.00,0.23,0
4,s1zzi,AWPer,83,0.57,0.47,0.32,0.77,0.63,0.93,0.33,0

In [38]:
feature_cols = [
    "firepower",
    "entrying",
    "trading",
    "opening",
    "clutching",
    "sniping",
    "utility",
    "igl",
]

# train_data = data.loc[data["igl"] == 0]
train_data = data

train_data.head()

,name,position,number_of_maps,firepower,entrying,trading,opening,clutching,sniping,utility,igl
0,alex666,Closer,83,0.27,0.44,0.43,0.26,0.58,0.00,0.61,1
1,npl,Opener,83,0.85,0.44,0.60,0.76,0.47,0.00,0.48,0
2,kensizor,Opener,83,0.70,0.94,0.56,0.63,0.37,0.00,0.41,0
3,esenthial,Linchpin,83,0.31,0.40,0.79,0.22,0.61,0.00,0.23,0
4,s1zzi,AWPer,83,0.57,0.47,0.32,0.77,0.63,0.93,0.33,0

In [39]:
X = train_data[feature_cols]
Y = train_data[["position", "number_of_maps"]]

Y.head()

   position  number_of_maps
0    Closer              83
1    Opener              83
2    Opener              83
3  Linchpin              83
4     AWPer              83

In [40]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y, test_size=0.25, random_state=16
)

In [41]:
import numpy as np
from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression(random_state=16)

sample_weight = np.log(Y_train["number_of_maps"])

clf = logreg.fit(X_train, Y_train["position"], sample_weight)

y_pred = clf.predict(X_test)

In [42]:
from sklearn.metrics import classification_report

target_names = ["AWPer", "Opener", "Closer", "Linchpin"]

print(classification_report(Y_test["position"], y_pred, target_names=target_names))

              precision    recall  f1-score   support

       AWPer       1.00      1.00      1.00         9
      Opener       0.80      0.36      0.50        11
      Closer       0.56      0.62      0.59         8
    Linchpin       0.71      0.94      0.81        16

    accuracy                           0.75        44
   macro avg       0.77      0.73      0.72        44
weighted avg       0.77      0.75      0.73        44

In [43]:
print(clf.predict(np.array([0.7, 0.2, 0.5, 0.2, 0.6, 0.9, 0.4, 0]).reshape(1, -1)))

['AWPer']

/home/archie955/cs2/server/.venv/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [44]:
print(clf.coef_, clf.intercept_)

# in order: AWPer, Closer, Linchpin, Opener
# features: ["firepower", "entrying", "trading", "opening", "clutching", "sniping", "utility"]

[[-0.10387905 -1.43014606  0.26921423  0.11488145  0.87152391  5.1162917
   0.28930523 -0.23923881]
 [ 0.31703357 -0.30784293  0.87139068 -0.19655824  0.92579171 -2.02534796
  -0.54117437  0.26416775]
 [-0.46264947 -0.01377692 -0.78372223 -3.36305653  0.43109501 -1.75928382
  -1.38050679 -1.90436143]
 [ 0.24949495  1.7517659  -0.35688268  3.44473332 -2.22841064 -1.33165992
   1.63237594  1.87943248]] [-1.94427201  0.330924    3.5902229  -1.97687489]

In [45]:
print(clf.classes_)

['AWPer' 'Closer' 'Linchpin' 'Opener']

In [46]:
print(clf.feature_names_in_)

['firepower' 'entrying' 'trading' 'opening' 'clutching' 'sniping'
 'utility' 'igl']

In [47]:
ropz = [0.70, 0.03, 0.46, 0.49, 0.49, 0.02, 0.22, 0.0]

ropz_df = np.array(ropz).reshape(1, -1)
print(clf.predict(ropz_df))

['Closer']

/home/archie955/cs2/server/.venv/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [48]:
def closer(p):
    total = clf.intercept_[1]
    for i in range(7):
        total += p[i] * clf.coef_[1][i]
    return total


def linchpin(p):
    total = clf.intercept_[2]
    for i in range(7):
        total += p[i] * clf.coef_[2][i]
    return total


def awper(p):
    total = clf.intercept_[0]
    for i in range(7):
        total += p[i] * clf.coef_[0][i]
    return total


def opener(p):
    total = clf.intercept_[3]
    for i in range(7):
        total += p[i] * clf.coef_[3][i]
    return total


print(
    f"Ropz closer rating is {closer(ropz)}, and his linchpin rating is {linchpin(ropz)}. His awper rating is {awper(ropz)} and his opener rating is {opener(ropz)}."
)

Ropz closer rating is 1.1422109981676039, and his linchpin rating is 1.1298844321839283. His awper rating is -1.2867415712896166 and his opener rating is -0.9853538590619386.

In [49]:
ratings = {
    "awper": awper(ropz),
    "closer": closer(ropz),
    "linchpin": linchpin(ropz),
    "opener": opener(ropz),
}

In [50]:
mini = 10
min_key = "null"
for key in ratings:
    if ratings[key] < mini:
        mini = ratings[key]
        min_key = key

for key in ratings:
    ratings[key] -= mini

## Merging closer/linchpin together

In [51]:
Y.replace("Linchpin", "Closer", inplace=True)

/tmp/ipykernel_2517/2431306730.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Y.replace("Linchpin", "Closer", inplace=True)

In [52]:
Y.head()

  position  number_of_maps
0   Closer              83
1   Opener              83
2   Opener              83
3   Closer              83
4    AWPer              83

In [53]:
X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y, test_size=0.25, random_state=16
)

logreg = LogisticRegression(random_state=16)

sample_weight = np.log(Y_train["number_of_maps"])

clf = logreg.fit(X_train, Y_train["position"], sample_weight)

y_pred = clf.predict(X_test)

In [54]:
target_names = ["AWPer", "Opener", "Closer"]

print(classification_report(Y_test["position"], y_pred, target_names=target_names))

              precision    recall  f1-score   support

       AWPer       1.00      1.00      1.00         9
      Opener       0.94      0.79      0.86        19
      Closer       0.79      0.94      0.86        16

    accuracy                           0.89        44
   macro avg       0.91      0.91      0.90        44
weighted avg       0.90      0.89      0.89        44

In [55]:
ropz = [0.70, 0.03, 0.46, 0.49, 0.49, 0.02, 0.22, 0.0]

ropz_df = np.array(ropz).reshape(1, -1)
print(clf.predict(ropz_df))

['Closer']

/home/archie955/cs2/server/.venv/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [56]:
def closer(p):
    total = clf.intercept_[1]
    for i in range(8):
        total += p[i] * clf.coef_[1][i]
    return total


def awper(p):
    total = clf.intercept_[0]
    for i in range(8):
        total += p[i] * clf.coef_[0][i]
    return total


def opener(p):
    total = clf.intercept_[2]
    for i in range(8):
        total += p[i] * clf.coef_[2][i]
    return total


print(
    f"Ropz closer rating is {closer(ropz)}. His awper rating is {awper(ropz)} and his opener rating is {opener(ropz)}."
)

Ropz closer rating is 2.21241135787477. His awper rating is -1.3330215103108038 and his opener rating is -0.8793898475639643.

# Multiple binary logistic classifiers

In [57]:
x1 = data[feature_cols]
y1 = data[["position", "number_of_maps"]]
y1.replace("Linchpin", "Not", inplace=True)
y1.replace("Closer", "Not", inplace=True)
y1.replace("Opener", "Not", inplace=True)
y1.head()

/tmp/ipykernel_2517/2853233111.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y1.replace("Linchpin", "Not", inplace=True)
/tmp/ipykernel_2517/2853233111.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y1.replace("Closer", "Not", inplace=True)
/tmp/ipykernel_2517/2853233111.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y1.replace("Opener", "Not", inplace=True)

  position  number_of_maps
0      Not              83
1      Not              83
2      Not              83
3      Not              83
4    AWPer              83

In [58]:
x1_train, x1_test, y1_train, y1_test = train_test_split(
    x1, y1, test_size=0.25, random_state=16
)

logreg1 = LogisticRegression(random_state=16)

sample_weight1 = np.log(y1_train["number_of_maps"])

clf = logreg1.fit(x1_train, y1_train["position"], sample_weight)

y1_pred = clf.predict(x1_test)

In [59]:
target_names = ["AWPer", "Not"]

print(classification_report(y1_test["position"], y1_pred, target_names=target_names))
print(clf.coef_)

              precision    recall  f1-score   support

       AWPer       1.00      1.00      1.00         9
         Not       1.00      1.00      1.00        35

    accuracy                           1.00        44
   macro avg       1.00      1.00      1.00        44
weighted avg       1.00      1.00      1.00        44

[[ 0.09930883  1.78824211 -0.292524   -0.2278416  -1.10480066 -6.45314129
  -0.37096662  0.68126223]]

In [60]:
y2 = data[["position", "number_of_maps"]]
y2.replace("AWPer", "Not", inplace=True)
y2.replace("Closer", "Not", inplace=True)
y2.replace("Opener", "Not", inplace=True)
y2.head()

x_train, x_test, y_train, y_test = train_test_split(
    x1, y2, test_size=0.25, random_state=16
)

logreg = LogisticRegression(random_state=16)

sample_weight = np.log(y_train["number_of_maps"])

clf = logreg.fit(x_train, y_train["position"], sample_weight)

y_pred = clf.predict(x_test)

target_names = ["Linchpin", "Not"]

print(classification_report(y_test["position"], y_pred, target_names=target_names))
print(clf.coef_)

              precision    recall  f1-score   support

    Linchpin       0.50      0.38      0.43         8
         Not       0.87      0.92      0.89        36

    accuracy                           0.82        44
   macro avg       0.68      0.65      0.66        44
weighted avg       0.80      0.82      0.81        44

[[ 0.56417972  0.26602882  0.97486952  4.25893787 -0.46196402  2.97469777
   1.63899091  2.7070392 ]]

/tmp/ipykernel_2517/506196202.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y2.replace("AWPer", "Not", inplace=True)
/tmp/ipykernel_2517/506196202.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y2.replace("Closer", "Not", inplace=True)
/tmp/ipykernel_2517/506196202.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y2.replace("Opener", "Not", inplace=True)

In [61]:
y = data[["position", "number_of_maps"]]
y.replace("Linchpin", "Not", inplace=True)
y.replace("AWPer", "Not", inplace=True)
y.replace("Opener", "Not", inplace=True)
y.head()

x_train, x_test, y_train, y_test = train_test_split(
    x1, y, test_size=0.25, random_state=16
)

logreg = LogisticRegression(random_state=16)

sample_weight = np.log(y_train["number_of_maps"])

clf = logreg.fit(x_train, y_train["position"], sample_weight)

y_pred = clf.predict(x_test)

target_names = ["Closer", "Not"]

print(classification_report(y_test["position"], y_pred, target_names=target_names))
print(clf.coef_)

              precision    recall  f1-score   support

      Closer       0.00      0.00      0.00        11
         Not       0.75      1.00      0.86        33

    accuracy                           0.75        44
   macro avg       0.38      0.50      0.43        44
weighted avg       0.56      0.75      0.64        44

[[-0.73091432  0.74578054 -1.33693207  0.70766847 -1.01365868  3.21319257
   0.59588707  0.47459823]]

/tmp/ipykernel_2517/1790728100.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y.replace("Linchpin", "Not", inplace=True)
/tmp/ipykernel_2517/1790728100.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y.replace("AWPer", "Not", inplace=True)
/tmp/ipykernel_2517/1790728100.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y.replace("Opener", "Not", inplace=True)
/home/archie955/cs2/server/.venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/home/archie955/cs2/server/.venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/home/archie955/cs2/server/.venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [62]:
y = data[["position", "number_of_maps"]]
y.replace("Linchpin", "Not", inplace=True)
y.replace("AWPer", "Not", inplace=True)
y.replace("Closer", "Not", inplace=True)
y.head()

x_train, x_test, y_train, y_test = train_test_split(
    x1, y, test_size=0.25, random_state=16
)

logreg = LogisticRegression(random_state=16)

sample_weight = np.log(y_train["number_of_maps"])

clf = logreg.fit(x_train, y_train["position"], sample_weight)

y_pred = clf.predict(x_test)

target_names = ["Opener", "Not"]

print(classification_report(y_test["position"], y_pred, target_names=target_names))
print(clf.coef_)

              precision    recall  f1-score   support

      Opener       0.93      0.89      0.91        28
         Not       0.82      0.88      0.85        16

    accuracy                           0.89        44
   macro avg       0.87      0.88      0.88        44
weighted avg       0.89      0.89      0.89        44

[[ 0.42770702  2.18654088 -0.54036808  4.09075762 -2.93300441 -2.61923907
   2.1498843   2.21047604]]

/tmp/ipykernel_2517/1988672175.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y.replace("Linchpin", "Not", inplace=True)
/tmp/ipykernel_2517/1988672175.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y.replace("AWPer", "Not", inplace=True)
/tmp/ipykernel_2517/1988672175.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y.replace("Closer", "Not", inplace=True)

In [63]:
y = data[["position", "number_of_maps"]]
y.replace("Linchpin", "Closer", inplace=True)
y.replace("AWPer", "Not", inplace=True)
y.replace("Opener", "Not", inplace=True)
y.head()

x_train, x_test, y_train, y_test = train_test_split(
    x1, y, test_size=0.25, random_state=16
)

logreg = LogisticRegression(random_state=16)

sample_weight = np.log(y_train["number_of_maps"])

clf = logreg.fit(x_train, y_train["position"], sample_weight)

y_pred = clf.predict(x_test)

target_names = ["Closer", "Not"]

print(classification_report(y_test["position"], y_pred, target_names=target_names))
print(clf.coef_)

              precision    recall  f1-score   support

      Closer       0.94      0.79      0.86        19
         Not       0.86      0.96      0.91        25

    accuracy                           0.89        44
   macro avg       0.90      0.87      0.88        44
weighted avg       0.89      0.89      0.88        44

[[-0.04733098  1.30560694 -0.31120513  4.27316981 -2.07167869  4.98074198
   2.24308587  1.98665665]]

/tmp/ipykernel_2517/1868326263.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y.replace("Linchpin", "Closer", inplace=True)
/tmp/ipykernel_2517/1868326263.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y.replace("AWPer", "Not", inplace=True)
/tmp/ipykernel_2517/1868326263.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y.replace("Opener", "Not", inplace=True)